spring:
  application:
    name: ecommerce-analytics-api
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_analytics}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # For demo, recreate schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Flyway Configuration - disabled for demo
  flyway:
    enabled: false
  
  # Redis Configuration (optional for demo)
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   password: ${REDIS_PASSWORD:}
  #   timeout: 2000ms
  #   jedis:
  #     pool:
  #       max-active: 8
  #       max-idle: 8
  #       min-idle: 0
  
  # Kafka Configuration (optional for demo)
  # kafka:
  #   bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.analytics.dto"

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: 86400000  # 24 hours

# Cache Configuration
cache:
  ttl:
    dashboard-metrics: 300  # 5 minutes
    product-metrics: 600   # 10 minutes
    sales-data: 180       # 3 minutes

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.ecommerce.analytics: INFO
    org.springframework.kafka: WARN
    org.flywaydb: INFO